# Generated by Django 5.2.4 on 2025-08-03 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bugmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bugmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
